version: "3"
services:
  pruebaMongoDBV:
    image: mongo:latest
    container_name: "pruebaMongoDBV"
    ports: 
      - 27017:27017
  springboot-mongodbtestv:
    image: springboot-mongodbtestv:1.0
    container_name: springboot-mongodbtestv
    ports:
      - 8080:8080
    links:
      - pruebaMongoDBV